### ISSUE TITLE
Achievement Customizer 2

### ISSUE THREAD

**Issue by Reeemz** [narlock/TamoStudy#15]
The achievement Customizer 2 gets unlocked when you go to inventory and click on select.  
It also doesn't change the default background.

**Comment by narlock** [comment]
Hi MuuseK,

I don't seem to understand the point of your issue. When you purchase a background from the Shop, it will appear in your inventory. All you need to do is "change" the background (this could mean clicking select on your current background).

If you had two backgrounds, both functionalities seem to work. Is there any chance that you may be able to replicate the issue you are having?

Regards

**Comment by MuuseK** [comment]
The issue is that you don't to purchase any background from the shop to get the achievement. 
You have one item in your inventory by default, and you unlock Customizer 2 by simply clicking change on the default background.
