### ISSUE TITLE
TamoStudyStream Linux runtime window display bug

### ISSUE THREAD

**Issue by narlock** [narlock/TamoStudy#16]
Upon launching TamoStudyStream v0.1, Linux does not properly render the window as follows,

![image](https://user-images.githubusercontent.com/59890724/183314461-040adcd5-d370-4561-9db2-9fe5f8403405.png)

The correct image should look something like this (image from Windows 10)

![image](https://user-images.githubusercontent.com/59890724/183314491-850f50ff-643f-49eb-80b7-5967730b71c3.png)

**Comment by narlock** [comment]
![image](https://user-images.githubusercontent.com/59890724/183315248-6b91c651-3370-4b6f-be0e-1b502438fe50.png)

Works on macOS, credits to Aeina

**Comment by Shorent** [comment]
I was able to replicate this problem in the Eclipse IDE  by selecting the 
    Extract required libraries into generated JAR
 option when exporting the project as a runnable JAR.

I was able to fix this problem by selecting the 
    Package required libraries into generated JAR
 option when exporting the project
![Screenshot from 2022-08-08 00-06-18](https://user-images.githubusercontent.com/46882932/183343989-731e70c0-e21c-48d0-960e-6b55d1c4a9e6.png)

**Comment by Shorent** [comment]
False information ^
JFrame.setLocationRelativeTo() and JFrame.setLocation commands clash with linux in some way.
