### ISSUE TITLE
The timer seems to be slower than an actual timer (Tamo Study 4.2 and 4.2.1)

### ISSUE THREAD

**Issue by akkota** [narlock/TamoStudy#21]
I used tamo study along with a physical pomodoro timer and noticed that in 60 minute sessions, it tends to ring, i.e the timer finishes later than the physical timer by maybe about 30 seconds. It's not a big issue but I would appreciate it if it's solved!

**Comment by narlock** [comment]
I will definitely look into improving the timer. I would say it may also be based on all of the applications running concurrently on the computer, thus, possibly slowing the speed of TamoStudy down. In my personal testing, TamoStudy and a real pomodoro timer have only been off by a second or two.

I will look into improving the accuracy of the timer, but, it may only be minimal depending on your computer's performance.

**Comment by narlock** [comment]
To clarify too, the specifications of my computer are definitely overkill for running an application like TamoStudy, but may also be why it has never been a problem for me... I have an i7-8700 and 32 GB of ram... lol.

**Comment by akkota** [comment]
Hmm, my specifications are i5-10300 and 8GB of ram. It's not overkill definitely but I don't think it's bad either lol. I checked my task manager. Tamo Study seems to be using like half my CPU XD (40-50%) but doesn't use too much of my RAM. I'm not sure if it's a specification problem but it could be.

**Comment by narlock** [comment]
Oh yeah, that's definitely just as overkill lol. I'm not entirely sure in terms of optimizing Java Swing applications. It seems some users vary in terms of how much CPU usage the application uses. I will say though, that the Discord RPC does have a big impact on CPU usage since it has to send requests through Discord's API... In the next release there will be an addition to remove this feature, perhaps that will make the timer align better to your standard.

**Comment by narlock** [comment]
Update: I will be running some manual tests with some software and hardware timers today to see if there is a difference.

**Comment by narlock** [comment]
Adding additional testing to backlog

**Comment by narlock** [comment]
After closer inspection, it looks like there is a very rare chance that the system could experience "timer drift" (https://en.wikipedia.org/wiki/Clock_drift, funny enough similar to computer clocks)

Depending on the load of the computer, it could be that the application may just be ever so slightly behind a true clock... Based off of the amount of computations per second it could definitely ever so slightly change and thus result in slower speed. 

I suspect that the longer that you are studying for, how many applications are open, cpu usage, etc. all are potential impacts of timer drift.

In my personal tests, I have not seen any timer drift, but TamoStudy also only is taking less than 0% of my CPU (AMD Ryzen 5 2600, similar to my other machine using an M1 Pro chip)
