### ISSUE TITLE
Some assets not appearing

### ISSUE THREAD

**Issue by veronica21cruz** [narlock/TamoStudy#6]
When buying food for the Tamo, a confirmation message appears. However, the assets do not appear on this message; they are replaced with the Java logo. This occurs for each food item. The other assets still work though!

(I’m using Mac OS)

<img width="731" alt="Screen Shot 2021-05-19 at 10 08 22 AM" src="https://user-images.githubusercontent.com/72842355/118829129-dd6ff900-b88b-11eb-94c9-8e908c26522e.png">

**Comment by narlock** [comment]
Haha yeah,

It looks like I forgot to add the image icons on these screens. They will be fixed in the next implementation!!

Thank you Ronnie!!!!!
